function h = calculatePropensity0x8E(X)

% Define ks:
ka = 0.25;       % Activated production rate
ka_f = 0.0033;   % Forward activation binding rate
ka_r = 1.0;      % Reverse activation binding rate
kao_f = 1.0;     % Forward activated RNAP binding rate
kao_r = 1.0;     % Reverse activated RNAP binding rate
kb = 1.0E-4;     % Basal production rate
kc_f = 0.05;     % Forward complex formation rate
kc_r = 1.0;      % Reverse complex formation rate
kd = 7.5E-4;     % Degradation rate 
ko = 0.05;       % Open complex production rate
ko_f = 0.033;    % Forward RNAP binding rate
ko_r = 1.0;      % Reverse RNAP binding rate
kr_f = 0.5;      % Forward repression binding rate
kr_r = 1.0;      % Reverse repression binding rate
nc = 2.0;        % Stoichiometry of binding
ng = 2.0;        % Initial promoter count
np = 10.0;       % Stoichiometry of production
nr = 30.0;       % Initial RNAP count

topModel_AmtRpart_module_sub__ka = 0.25;    
topModel_AmtRpart_module_sub__ka_f = 0.0033; 
topModel_AmtRpart_module_sub__ka_r = 1;
topModel_AmtRpart_module_sub__kao_f = 1;
topModel_AmtRpart_module_sub__kao_r = 1;
topModel_AmtRpart_module_sub__kb = 1.0E-4;
topModel_AmtRpart_module_sub__ko = 0.05;
topModel_AmtRpart_module_sub__ko_f = 0.033;
topModel_AmtRpart_module_sub__ko_r = 1;
topModel_AmtRpart_module_sub__kr_f = 0.5;
topModel_AmtRpart_module_sub__kr_r = 1;
topModel_AmtRpart_module_sub__nc = 2;
topModel_AmtRpart_module_sub__ng = 2;
topModel_AmtRpart_module_sub__np = 10;
topModel_AmtRpart_module_sub__nr = 30;
topModel_BetIpart_module_sub__ka = 0.25;
topModel_BetIpart_module_sub__ka_f = 0.0033;
topModel_BetIpart_module_sub__ka_r = 1;
topModel_BetIpart_module_sub__kao_f = 1;
topModel_BetIpart_module_sub__kao_r = 1;
topModel_BetIpart_module_sub__kb = 1.0E-4;
topModel_BetIpart_module_sub__ko = 0.05;
topModel_BetIpart_module_sub__ko_f = 0.033;
topModel_BetIpart_module_sub__ko_r = 1;
topModel_BetIpart_module_sub__kr_f = 0.5;
topModel_BetIpart_module_sub__kr_r = 1;
topModel_BetIpart_module_sub__nc = 2;
topModel_BetIpart_module_sub__ng = 2;
topModel_BetIpart_module_sub__np = 10;
topModel_BetIpart_module_sub__nr = 30;
topModel_HlyIIRpart_module_sub__ka = 0.25;
topModel_HlyIIRpart_module_sub__ka_f = 0.0033;
topModel_HlyIIRpart_module_sub__ka_r = 1;
topModel_HlyIIRpart_module_sub__kao_f = 1;
topModel_HlyIIRpart_module_sub__kao_r = 1;
topModel_HlyIIRpart_module_sub__kb = 1.0E-4;
topModel_HlyIIRpart_module_sub__ko = 0.05;
topModel_HlyIIRpart_module_sub__ko_f = 0.033;
topModel_HlyIIRpart_module_sub__ko_r = 1;
topModel_HlyIIRpart_module_sub__kr_f = 0.5;
topModel_HlyIIRpart_module_sub__kr_r = 1;
topModel_HlyIIRpart_module_sub__nc = 2;
topModel_HlyIIRpart_module_sub__ng = 2;
topModel_HlyIIRpart_module_sub__np = 10;
topModel_HlyIIRpart_module_sub__nr = 30;
topModel_PhlFpart_module_sub__ka = 0.25;
topModel_PhlFpart_module_sub__ka_f = 0.0033;
topModel_PhlFpart_module_sub__ka_r = 1;
topModel_PhlFpart_module_sub__kao_f = 1;
topModel_PhlFpart_module_sub__kao_r = 1;
topModel_PhlFpart_module_sub__kb = 1.0E-4;
topModel_PhlFpart_module_sub__ko = 0.05;
topModel_PhlFpart_module_sub__ko_f = 0.033;
topModel_PhlFpart_module_sub__ko_r = 1;
topModel_PhlFpart_module_sub__kr_f = 0.5;
topModel_PhlFpart_module_sub__kr_r = 1;
topModel_PhlFpart_module_sub__nc = 2;
topModel_PhlFpart_module_sub__ng = 2;
topModel_PhlFpart_module_sub__np = 10;
topModel_PhlFpart_module_sub__nr = 30;
topModel_YFPpart_module_sub__ka = 0.25;
topModel_YFPpart_module_sub__ka_f = 0.0033;
topModel_YFPpart_module_sub__ka_r = 1;
topModel_YFPpart_module_sub__kao_f = 1;
topModel_YFPpart_module_sub__kao_r = 1;
topModel_YFPpart_module_sub__kb = 1.0E-4;
topModel_YFPpart_module_sub__ko = 0.05;
topModel_YFPpart_module_sub__ko_f = 0.033;
topModel_YFPpart_module_sub__ko_r = 1;
topModel_YFPpart_module_sub__kr_f = 0.5;
topModel_YFPpart_module_sub__kr_r = 1;
topModel_YFPpart_module_sub__nc = 2;
topModel_YFPpart_module_sub__ng = 2;
topModel_YFPpart_module_sub__np = 10;
topModel_YFPpart_module_sub__nr = 30;



% Reaction Propensities
h(1,1) = kd*X(1); % AmtR_degradation_interaction
h(2,1) = kd*X(3); % BetI_degradation_interaction
h(3,1) = kd*X(4); % HlyIIR_degradation_interaction
h(4,1) = kd*X(6); % PhlF_degradation_interaction
h(5,1) = X(9)*(topModel_AmtRpart_module_sub__kb*topModel_AmtRpart_module_sub__ko_f/topModel_AmtRpart_module_sub__ko_r*topModel_AmtRpart_module_sub__nr+topModel_AmtRpart_module_sub__ka*topModel_AmtRpart_module_sub__kao_f/topModel_AmtRpart_module_sub__kao_r*topModel_AmtRpart_module_sub__nr*(topModel_AmtRpart_module_sub__ka_f/topModel_AmtRpart_module_sub__ka_r*X(2))^topModel_AmtRpart_module_sub__nc)/(1+topModel_AmtRpart_module_sub__ko_f/topModel_AmtRpart_module_sub__ko_r*topModel_AmtRpart_module_sub__nr+topModel_AmtRpart_module_sub__kao_f/topModel_AmtRpart_module_sub__kao_r*topModel_AmtRpart_module_sub__nr*(topModel_AmtRpart_module_sub__ka_f/topModel_AmtRpart_module_sub__ka_r*X(2))^topModel_AmtRpart_module_sub__nc); % topModel_AmtRpart_module_sub__X(1)_interaction_0
h(6,1) = X(10)*topModel_AmtRpart_module_sub__ko*topModel_AmtRpart_module_sub__ko_f/topModel_AmtRpart_module_sub__ko_r*topModel_AmtRpart_module_sub__nr/(1+topModel_AmtRpart_module_sub__ko_f/topModel_AmtRpart_module_sub__ko_r*topModel_AmtRpart_module_sub__nr+(topModel_AmtRpart_module_sub__kr_f/topModel_AmtRpart_module_sub__kr_r*X(4))^topModel_AmtRpart_module_sub__nc); % topModel_AmtRpart_module_sub__X(1)_interaction_1
h(7,1) = X(11)*topModel_BetIpart_module_sub__ko*topModel_BetIpart_module_sub__ko_f/topModel_BetIpart_module_sub__ko_r*topModel_BetIpart_module_sub__nr/(1+topModel_BetIpart_module_sub__ko_f/topModel_BetIpart_module_sub__ko_r*topModel_BetIpart_module_sub__nr+(topModel_BetIpart_module_sub__kr_f/topModel_BetIpart_module_sub__kr_r*X(4))^topModel_BetIpart_module_sub__nc); % topModel_BetIpart_module_sub__X(3)_interaction_0
h(8,1) = X(12)*topModel_BetIpart_module_sub__ko*topModel_BetIpart_module_sub__ko_f/topModel_BetIpart_module_sub__ko_r*topModel_BetIpart_module_sub__nr/(1+topModel_BetIpart_module_sub__ko_f/topModel_BetIpart_module_sub__ko_r*topModel_BetIpart_module_sub__nr+(topModel_BetIpart_module_sub__kr_f/topModel_BetIpart_module_sub__kr_r*X(7))^topModel_BetIpart_module_sub__nc); % topModel_BetIpart_module_sub__X(3)_interaction_1
h(9,1) = X(14)*(topModel_HlyIIRpart_module_sub__kb*topModel_HlyIIRpart_module_sub__ko_f/topModel_HlyIIRpart_module_sub__ko_r*topModel_HlyIIRpart_module_sub__nr+topModel_HlyIIRpart_module_sub__ka*topModel_HlyIIRpart_module_sub__kao_f/topModel_HlyIIRpart_module_sub__kao_r*topModel_HlyIIRpart_module_sub__nr*(topModel_HlyIIRpart_module_sub__ka_f/topModel_HlyIIRpart_module_sub__ka_r*X(2))^topModel_HlyIIRpart_module_sub__nc)/(1+topModel_HlyIIRpart_module_sub__ko_f/topModel_HlyIIRpart_module_sub__ko_r*topModel_HlyIIRpart_module_sub__nr+topModel_HlyIIRpart_module_sub__kao_f/topModel_HlyIIRpart_module_sub__kao_r*topModel_HlyIIRpart_module_sub__nr*(topModel_HlyIIRpart_module_sub__ka_f/topModel_HlyIIRpart_module_sub__ka_r*X(2))^topModel_HlyIIRpart_module_sub__nc); % topModel_HlyIIRpart_module_sub__HlyIIR_protein_interaction_0
h(10,1) = X(11)*topModel_HlyIIRpart_module_sub__ko*topModel_HlyIIRpart_module_sub__ko_f/topModel_HlyIIRpart_module_sub__ko_r*topModel_HlyIIRpart_module_sub__nr/(1+topModel_HlyIIRpart_module_sub__ko_f/topModel_HlyIIRpart_module_sub__ko_r*topModel_HlyIIRpart_module_sub__nr+(topModel_HlyIIRpart_module_sub__kr_f/topModel_HlyIIRpart_module_sub__kr_r*X(7))^topModel_HlyIIRpart_module_sub__nc); % topModel_HlyIIRpart_module_sub__HlyIIR_protein_interaction_1
h(11,1) = X(16)*ko*ko_f/ko_r*nr/(1+ko_f/ko_r*nr+(kr_f/kr_r*X(5))^nc); % topModel_PhlFpart_module_sub__X(6)_interaction_0                                                                                                     
h(12,1) = X(15)*topModel_PhlFpart_module_sub__ko*topModel_PhlFpart_module_sub__ko_f/topModel_PhlFpart_module_sub__ko_r*topModel_PhlFpart_module_sub__nr/(1+topModel_PhlFpart_module_sub__ko_f/topModel_PhlFpart_module_sub__ko_r*topModel_PhlFpart_module_sub__nr+(topModel_PhlFpart_module_sub__kr_f/topModel_PhlFpart_module_sub__kr_r*X(1))^topModel_PhlFpart_module_sub__nc); % topModel_PhlFpart_module_sub__X(6)_interaction_1                                                                                                          
h(13,1) = X(18)*topModel_YFPpart_module_sub__ko*topModel_YFPpart_module_sub__ko_f/topModel_YFPpart_module_sub__ko_r*topModel_YFPpart_module_sub__nr/(1+topModel_YFPpart_module_sub__ko_f/topModel_YFPpart_module_sub__ko_r*topModel_YFPpart_module_sub__nr+(topModel_YFPpart_module_sub__kr_f/topModel_YFPpart_module_sub__kr_r*X(6))^topModel_YFPpart_module_sub__nc); % topModel_YFPpart_module_sub__YFP_protein_interaction_0                                                                                                        
h(14,1) = X(17)*topModel_YFPpart_module_sub__ko*topModel_YFPpart_module_sub__ko_f/topModel_YFPpart_module_sub__ko_r*topModel_YFPpart_module_sub__nr/(1+topModel_YFPpart_module_sub__ko_f/topModel_YFPpart_module_sub__ko_r*topModel_YFPpart_module_sub__nr+(topModel_YFPpart_module_sub__kr_f/topModel_YFPpart_module_sub__kr_r*X(3))^topModel_YFPpart_module_sub__nc); % topModel_YFPpart_module_sub__YFP_protein_interaction_1                                                                                                         
h(15,1) = kd*X(8); % YFP_degradation_interaction                                                                                                        

end
